### ISSUE TITLE
Export backup button doesn't export anything

### ISSUE THREAD

**Issue by olivertzeng** [Luki120/Azure#13]

**Comment by Luki120** [comment]
This isn’t providing any useful information, like device iOS version, jailbreak, maybe a video, etc

**Comment by olivertzeng** [comment]
> This isn’t providing any useful information, like device iOS version, jailbreak, maybe a video, etc

Whoops sorry
I’m on iPhone 14 iOS 16.5 with Seretonin

**Comment by Luki120** [comment]
Please try [this](https://workupload.com/file/tJhmbs7h9hQ), should work now

**Comment by olivertzeng** [comment]
> Please try [this](https://workupload.com/file/6zuggZ3FTuP), should work now

The yes button when trying to access the backup from filza does nothing

**Comment by olivertzeng** [comment]
> Please try [this](https://workupload.com/file/6zuggZ3FTuP), should work now

![image](https://github.com/Luki120/Azure/assets/86348833/66c82cd2-e2f7-4ed6-9e92-bbc8bb702b32)![image](https://github.com/Luki120/Azure/assets/86348833/ef070dd8-9559-4c88-b7b5-07c2e7fc8543)

**Comment by olivertzeng** [comment]
Wait nothing it was fixed thanks

**Comment by Luki120** [comment]
Great, will push the update soon then
