### ISSUE TITLE
Update to your repo

### ISSUE THREAD

**Issue by olivertzeng** [Luki120/Azure#14]
I can't see the new 1.9.4 Azure on the repo
Or do you have the latest beta repo?

**Comment by Luki120** [comment]
I pushed this code less than a day ago, updating the repo 5 minutes after depends on my availability & the things I have to do. Here's a [deb](https://workupload.com/file/CHCCmSBabcm) I saved for something else, next time either wait or compile the project yourself, but please don't open issues about things that aren't issues, thank you

**Comment by olivertzeng** [comment]
Thanks for replying! I’ll try to DIY the deb for myself next time!
 Sent from Proton Mail for iOS 
於 週日, 3月 31, 2024 時間 21:40, Luki120 ***@***.***&gt; 寫道：  I pushed this code less than a day ago, updating the repo 5 minutes after depends on my availability &amp; the things I have to do. Here's a deb I saved for something else, next time either wait or compile the project yourself, but please don't open issues about things that aren't issues, thank you
